# Colors
set -g @bg_default "#1e1e2e"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
set-window-option -g mode-keys vi
set -s escape-time 0

# switch panes using Alt-arrow without prefix
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

unbind x
unbind &
bind x run-shell "tmux kill-pane"
bind & run-shell "tmux kill-window"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g cursor-style bar

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour '#a6e3a1'

# copy mode
setw -g mode-style 'fg=#45475a bg=#f38ba8 bold'

# panes
set -g pane-border-style 'fg=#c6d0f5'
set -g pane-active-border-style 'fg=#cba6f7'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=#45475a bg=#a6e3a1'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=#45475a bold bg=#cba6f7 bold'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=#fab387 bg=#1e1e2e'
setw -g window-status-format ' #I #[fg=#bac2de]#W #[fg=#fab387]#F '

setw -g window-status-bell-style 'fg=yellow bg=#1e1e2e bold'

# messages
set -g message-style 'fg=#45475a bg=#f38ba8 bold'
